version: '3.9'

x-chatwoot-build: &chatwoot-build
  build:
    context: .
    dockerfile: docker/Dockerfile
  image: chatwoot:${SOURCE_COMMIT:-latest}

services:
  chatwoot:
    <<: *chatwoot-build
    env_file:
      - .env.external
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - RAILS_ENV=${RAILS_ENV:-production}
      - INSTALLATION_ENV=${INSTALLATION_ENV:-docker}
    ports:
      - "${CHATWOOT_LISTEN:-3000}:3000"
    volumes:
      - storage_data:/app/storage
      - packs_data:/app/public/packs
    entrypoint: docker/entrypoints/rails.sh
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]
    restart: always

  sidekiq:
    <<: *chatwoot-build
    env_file:
      - .env.external
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - RAILS_ENV=${RAILS_ENV:-production}
      - INSTALLATION_ENV=${INSTALLATION_ENV:-docker}
    volumes:
      - storage_data:/app/storage
      - packs_data:/app/public/packs
    command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
    restart: always

volumes:
  storage_data:
  packs_data:
