version: '3.9'

services:
  chatwoot:
    image: ${CHATWOOT_IMAGE:-romsribn/chatwoot-poker:latest}
    depends_on:
      - postgres
      - redis
    environment:
      - SECRET_KEY_BASE=${SECRET_KEY_BASE:?SECRET_KEY_BASE is required}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
      - ENABLE_ACCOUNT_SIGNUP=${ENABLE_ACCOUNT_SIGNUP:-false}
      - FORCE_SSL=${FORCE_SSL:-false}
      - DEFAULT_LOCALE=${DEFAULT_LOCALE:-en}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis_password}
      - REDIS_URL=${REDIS_URL:-redis://default:${REDIS_PASSWORD:-redis_password}@${REDIS_HOST:-redis}:6379/0}
      - REDIS_OPENSSL_VERIFY_MODE=${REDIS_OPENSSL_VERIFY_MODE:-none}
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-chatwoot}
      - POSTGRES_DATABASE=${POSTGRES_DB:-chatwoot}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_USERNAME=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - DATABASE_URL=${DATABASE_URL:-postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_HOST:-postgres}:5432/${POSTGRES_DB:-chatwoot}}
      - RAILS_MAX_THREADS=${RAILS_MAX_THREADS:-5}
      - NODE_ENV=${NODE_ENV:-production}
      - RAILS_ENV=${RAILS_ENV:-production}
      - INSTALLATION_ENV=${INSTALLATION_ENV:-docker}
      - MAILER_SENDER_EMAIL=${MAILER_SENDER_EMAIL:-Chatwoot <accounts@example.com>}
      - SMTP_ADDRESS=${SMTP_ADDRESS:-}
      - SMTP_AUTHENTICATION=${SMTP_AUTHENTICATION:-}
      - SMTP_DOMAIN=${SMTP_DOMAIN:-}
      - SMTP_ENABLE_STARTTLS_AUTO=${SMTP_ENABLE_STARTTLS_AUTO:-true}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USERNAME=${SMTP_USERNAME:-}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-}
      - ACTIVE_STORAGE_SERVICE=${ACTIVE_STORAGE_SERVICE:-local}
    ports:
      - "${CHATWOOT_PORT:-3000}:3000"
    volumes:
      - rails-data:/app/storage
      - rails-assets:/app/public/packs
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:3000"]
      interval: 5s
      timeout: 20s
      retries: 10

  sidekiq:
    image: ${CHATWOOT_IMAGE:-romsribn/chatwoot-poker:latest}
    depends_on:
      - postgres
      - redis
    environment:
      - SECRET_KEY_BASE=${SECRET_KEY_BASE:?SECRET_KEY_BASE is required}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
      - ENABLE_ACCOUNT_SIGNUP=${ENABLE_ACCOUNT_SIGNUP:-false}
      - FORCE_SSL=${FORCE_SSL:-false}
      - DEFAULT_LOCALE=${DEFAULT_LOCALE:-en}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis_password}
      - REDIS_URL=${REDIS_URL:-redis://default:${REDIS_PASSWORD:-redis_password}@${REDIS_HOST:-redis}:6379/0}
      - REDIS_OPENSSL_VERIFY_MODE=${REDIS_OPENSSL_VERIFY_MODE:-none}
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-chatwoot}
      - POSTGRES_DATABASE=${POSTGRES_DB:-chatwoot}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_USERNAME=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - DATABASE_URL=${DATABASE_URL:-postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_HOST:-postgres}:5432/${POSTGRES_DB:-chatwoot}}
      - RAILS_MAX_THREADS=${RAILS_MAX_THREADS:-5}
      - NODE_ENV=${NODE_ENV:-production}
      - RAILS_ENV=${RAILS_ENV:-production}
      - INSTALLATION_ENV=${INSTALLATION_ENV:-docker}
      - MAILER_SENDER_EMAIL=${MAILER_SENDER_EMAIL:-Chatwoot <accounts@example.com>}
      - SMTP_ADDRESS=${SMTP_ADDRESS:-}
      - SMTP_AUTHENTICATION=${SMTP_AUTHENTICATION:-}
      - SMTP_DOMAIN=${SMTP_DOMAIN:-}
      - SMTP_ENABLE_STARTTLS_AUTO=${SMTP_ENABLE_STARTTLS_AUTO:-true}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USERNAME=${SMTP_USERNAME:-}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-}
      - ACTIVE_STORAGE_SERVICE=${ACTIVE_STORAGE_SERVICE:-local}
    entrypoint: ["/app/docker-entrypoint.sh"]
    command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
    volumes:
      - rails-data:/app/storage
      - rails-assets:/app/public/packs
    healthcheck:
      test: ["CMD-SHELL", "bundle exec rails runner 'puts Sidekiq.redis(&:info)' > /dev/null 2>&1"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: ${POSTGRES_IMAGE:-pgvector/pgvector:pg16}
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-chatwoot}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-chatwoot} -h 127.0.0.1"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: ${REDIS_IMAGE:-redis:alpine}
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis_password}
    command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "PING"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  rails-data:
  rails-assets:
  postgres-data:
  redis-data:
